### ISSUE TITLE
Pass Sources Root folders as LSP workspaceFolders

### ISSUE THREAD

**Issue by not-my-profile** [InSyncWithFoo/pyright-langserver-for-pycharm#18]
Pyright only supports pyrightconfig.json files at the root of an LSP workspace. I'd like pyright to recognize `pyrightconfig.json` files in Source Root folders. This plugin currently uses `ProjectWideLspServerDescriptor`:

https://github.com/InSyncWithFoo/pyright-langserver-for-pycharm/blob/d1f409b016da82d5573ed2bbb19e6128e3958b7f/src/main/kotlin/com/insyncwithfoo/pyrightls/server/PyrightLSDescriptor.kt#L14-L17

I think we can instead inherit

```kotlin
LspServerDescriptor(project, PRESENTABLE_NAME, *project.modules.flatMap { m -> ModuleRootManager.getInstance(m).sourceRoots.asIterable() }.toTypedArray())
```

**Comment by InSyncWithFoo** [comment]
Seems easy enough to implement. I'll get back with a PR in a few hours.

**Comment by InSyncWithFoo** [comment]
Done. Try the build out and let me know what you think.

**Comment by not-my-profile** [comment]
Thanks it's working :)

Small feedback regarding "Project base directories": can there really be multiple? I think there can only be one project base directory, so this should be singular?

If that's the case I think source roots should be the default setting since it's more flexible. Maybe it would also make sense to document this in the README because users might be confused why their `pyrightconfig.json` has no effect.

**Comment by InSyncWithFoo** [comment]
> Small feedback regarding "Project base directories": can there really be multiple?

According to [`com/intellij/openapi/project/BaseProjectDirectories.kt`](https://github.com/JetBrains/intellij-community/blob/ae94bab27d00b6135f729e16a7e6b7a6fe5128b4/platform/ide-core/src/com/intellij/openapi/project/BaseProjectDirectories.kt#L18-L24), that wouldn't happen most of the times, but it's still a possibility.

> [...] I think source roots should be the default setting since it's more flexible.

I'm not sure about this (no matter the number of project base directories). Most Python projects of mine don't even have a "source root", and when they do, it's often `src` directories (as in [the `src` layout](https://packaging.python.org/en/latest/discussions/src-layout-vs-flat-layout/)) which never contains `pyproject.toml` or `pyrightconfig.json`. This setting was made to be project-based for this very reason.

In short, I prefer to keep the current default, since:

* There is no strong evidence that most users want it not to be, and
* So far, it is the most comfortable choice for <em>me</em>.

While this plugin is intended to be used by the general public, I only ever have experience about how I use it myself. Of course, all users are welcome to voice their opinions using Marketplace reviews, GitHub issues/discussions/PRs (like this one) or even personal emails.

On the other hand, precooked options seem a bit (you guessed it) inflexible. I thought of adding a whole form like [this](https://github.com/detekt/detekt-intellij-plugin/blob/070b8d09a0fb94321e299aa8854078f9188daf03/src/main/kotlin/io/gitlab/arturbosch/detekt/idea/config/ui/DetektConfigUi.kt#L176-L184), but that would probably be overkill.

![](https://github.com/InSyncWithFoo/pyright-langserver-for-pycharm/assets/122007197/a4ece41f-8705-4bf1-9dc4-34156103b737)

**Comment by not-my-profile** [comment]
Thanks ... that makes sense to me. I was mainly confused by the *Project Structure* settings UI ... if you click *Add Content Root* there it looks like you removed the previous one. I agree that a separate path management would be unwieldy / unnecessary.

I think it would be nice if we could add some help text under the option to explain sth like:

> pyright will only recognize pyrightconfig.json (or pyproject.toml) files residing directly in these directories.
