### ISSUE TITLE
use the same plugin for both pycharm community and professional versions

### ISSUE THREAD

**Issue by DetachHead** [InSyncWithFoo/pyright-langserver-for-pycharm#22]
### Feature or enhancement

the ruff plugin seems to conditionally use the language server if the user is on pycharm professional: https://github.com/koxudaxi/ruff-pycharm-plugin/blob/befe74aa4558a348c968f66b64e9374fe6b38a6b/resources/META-INF/plugin.xml#L9

### Proposed solution

- if the user is on pycharm community, fallback to the functionality from the https://github.com/InSyncWithFoo/pyright-for-pycharm
- if the user is on pycharm professional, use the language server

### Additional context

i work in a team where some users have community and some users have professional. i want to specify this plugin in the "required plugins" list for the project so that users are prompted to install it, but that won't work because depending on which version of pycharm they're using, they'll need to install a different plugin

**Comment by InSyncWithFoo** [comment]
I have already published these two as separate plugins, and although this was most likely a bad decision on my part, there's no going back.

If I were to merge them now, one of the repositories and one of the Marketplace entries will have to be archived/deleted (this one's), which is undesired since the LSP API is still experimental (meta-speaking, probably [sunk cost fallacy](https://en.wikipedia.org/wiki/Sunk_cost) too). That said, I would prefer it if I don't have to do this [right now](https://peps.python.org/pep-0020/).

Closing, but will reopen in the future.
