### ISSUE TITLE
Enhanced lambda support.

### ISSUE THREAD

**Issue by Ayfri** [InSyncWithFoo/pyright-langserver-for-pycharm#57]
### Feature or enhancement

Hey, I love so much the auto-complete feature about lambdas that your plugin pretty much has, with a small issue !
Currently, you have to write at least one character before having auto-complete of lambda arguments :
![image](https://github.com/InSyncWithFoo/pyright-langserver-for-pycharm/assets/34159136/7869e4c6-db6f-4353-bbff-54898ab94434)

Also, a bit unrelated, but it would be very very cool if you extract this feature into a small plugin, just so that we don't have to use PyRight. It's a very [big known issue](https://youtrack.jetbrains.com/issue/PY-28130/lambda-type-hinting-based-on-its-usage), preventing me from using lambdas at all in my projects (I could now with PyRight, but I used some weird hacks on python that PyRight doesn't like at all haha).

### Proposed solution

It would be very cool to not have the first-character constraint and have full auto-complete.

And also a separate plugin.

### Additional context

The plugin I'm using for inlay hints of variables is this https://plugins.jetbrains.com/plugin/19538-python-inlay-params, it would also be very nice if you could collaborate so that lambdas show the types of parameters like in other languages.
![image](https://github.com/InSyncWithFoo/pyright-langserver-for-pycharm/assets/34159136/9827a53b-3b5a-45aa-829b-8ee7a732080c)

**Comment by InSyncWithFoo** [comment]
I'm sorry, but this is out-of-scope for this plugin.

It is [intended](https://insyncwithfoo.github.io/pyright-for-pycharm/faq/#lsp) to connect two separate parts, the language server and your IDE, not to provide important features of its own. I do add some monkeypatches [here](https://github.com/InSyncWithFoo/pyright-langserver-for-pycharm/pull/50) and [there](https://github.com/InSyncWithFoo/pyright-langserver-for-pycharm/pull/52), but they are generally insignificant to the experience at large.

To add on top of that, the number of LSP features this plugin could provide is limited by two things:

1. The language server's own capabilities.

   For better `lambda` completion, you could ask for that at [@microsoft/pyright](https://github.com/microsoft/pyright) or [@microsoft/pylance-release](https://github.com/microsoft/pylance-release). Since this is not related to core type checking, my guess is that your issue would be moved to the latter's 300+ issues backlog if it were to be created at the former.

   Pyright [doesn't](https://microsoft.github.io/pyright/#/features?id=language-server-support) provide inlay hints. Its maintainers [have declared](https://github.com/microsoft/pyright/issues/4325) that they do not plan to add any new LSP features (as I understand, to avoid competing with the proprietary Pylance). There are forks that do this, like [@DetachHead/basedpyright](https://github.com/DetachHead/basedpyright) and [@jbradaric/pyright-inlay-hints](https://github.com/jbradaric/pyright-inlay-hints). However, even if you do use them, there's also...

3. The *experimental* LSP API's client capabilities.

   As of yet, it provides me with [7 features](https://plugins.jetbrains.com/docs/intellij/language-server-protocol.html#customization) to customize: [Go-to-definition](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_definition), [hover](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_hover), [completion](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_completion), [diagnostics](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_publishDiagnostics), [formatting](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_formatting), [code actions](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_codeAction) and [commands](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_executeCommand). Pyright itself doesn't provide the last three (not sure about the advertised "Organize imports"), and I have added support for all of the other four. The first two can only be toggled (using booleans).

I'm also [adopting LSP4IJ](https://github.com/InSyncWithFoo/pyright-for-pycharm/pull/42) via [this plugin's sister](https://github.com/InSyncWithFoo/pyright-for-pycharm), which provides many more customizations. That will take <em>a lot</em> of work, but when done (probably not after very long), this plugin will be deprecated and all of its features transferred (as a separate mode, using the same LSP API, so nothing is lost).

Having said all of that, please do look forward to the new, merged plugin. The next release of this plugin will probably be its last.
