### ISSUE TITLE
Bundle LSP with plugin

### ISSUE THREAD

**Issue by Martmists-GH** [InSyncWithFoo/pyright-langserver-for-pycharm#58]
### Feature or enhancement

Bundle the language server with the plugin. Not sure why this wasn't done in the first place since it'll benefit from working with the currently configured venv and the plugin is functionally useless without it.

### Proposed solution

It means I don't need to update them separately, nor do I need to install/uninstall separately.

**Comment by InSyncWithFoo** [comment]
I considered doing this when I started the project, however:

* Pyright gets a new release about every week. Its backing team at Microsoft can afford that; I can't.
* Pyright is written in JS/TS and thus requires Node, a huge dependency. If I were to avoid bundling Node, I should expect my users to have Node installed, but if they already have Node, asking them to install Pyright on their own is much easier.
* This plugin is composable/"duck-typed" by design. You can, for example, give it the executable of Pylance and it won't complain (to be clear, that would be illegal since Pylance is only ever licensed to be used within official Microsoft products).
